server:
  port: 8086
  servlet:
    context-path: /parkinglot



spring:
  data:
    mongodb:
      database: PARAM_NET
      port: 27017
      host: localhost
      repositories:
        enabled: true